/*
 * `next/image` static imports — `import shield from "…/shield-family.png"` — are typed
 * by this reference. Next writes the same line into `next-env.d.ts`, but that file is
 * generated by `next dev`/`next build` and gitignored, so `pnpm typecheck` on a clean
 * checkout (which is what CI runs, before any build) would not have it.
 */
/// <reference types="next/image-types/global" />
