#!/usr/bin/env bash
# Idempotent Cloud Agent bootstrap for FamilyFi.
# Docker is unavailable in the Cloud Agent VM, so PostgreSQL is installed
# directly as a system package instead of via docker-compose.
set -euo pipefail
cd "$(dirname "$0")/.."

# --- System dependency: PostgreSQL (Docker is not available in the VM) ---
if ! command -v pg_ctlcluster >/dev/null 2>&1; then
  sudo apt-get update -y
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y postgresql postgresql-contrib
fi

# Detect the installed cluster version instead of hard-coding it.
PG_VERSION="$(ls /etc/postgresql 2>/dev/null | sort -V | tail -1)"
PG_VERSION="${PG_VERSION:-16}"

# Start the cluster so we can provision the role/databases and migrate.
sudo pg_ctlcluster "$PG_VERSION" main start 2>/dev/null || true
for _ in $(seq 1 30); do
  if sudo -u postgres pg_isready -q; then break; fi
  sleep 1
done

# --- Provision the app role and databases (idempotent) ---
DB_PASSWORD="familyfi_dev_pw"
sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL
DO \$\$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='familyfi') THEN
    CREATE ROLE familyfi LOGIN PASSWORD '${DB_PASSWORD}';
  ELSE
    ALTER ROLE familyfi PASSWORD '${DB_PASSWORD}';
  END IF;
END \$\$;
ALTER ROLE familyfi CREATEDB;
SQL
sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='familyfi'" | grep -q 1 \
  || sudo -u postgres createdb -O familyfi familyfi
# familyfi_test backs `make test-integration`.
sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='familyfi_test'" | grep -q 1 \
  || sudo -u postgres createdb -O familyfi familyfi_test

# --- App .env (dev only; crypto secrets are auto-generated by the app scripts) ---
# .env is gitignored. UNIFI_MOCK seeds a dummy household so the UI is usable
# without a live UniFi console.
if [ ! -f .env ]; then
  cat > .env <<'ENV'
DB_MODE=bundled
DB_HOST=127.0.0.1
POSTGRES_PORT=5432
POSTGRES_DB=familyfi
POSTGRES_USER=familyfi
POSTGRES_PASSWORD=familyfi_dev_pw
UNIFI_MOCK=1
ENV
fi

# --- Node dependencies ---
corepack enable
npx --yes pnpm@10.15.1 install --frozen-lockfile

# --- Database schema + Prisma client ---
node scripts/with-env.mjs ./node_modules/.bin/prisma migrate deploy
node scripts/with-env.mjs ./node_modules/.bin/prisma generate

echo "FamilyFi install complete."
